### ISSUE TITLE
import WireDataModel not finding after pod install

### ISSUE THREAD

**Issue by DaniyalGeek** [wireapp/wire-ios#1123]
```#import <WireExtensionComponents/UserImageView.h>
        ^
/Users/apple/Downloads/wire-ios-develop/WireExtensionComponents/Views/UserImageView.h:19:9: error: module 'WireDataModel' not found
@import WireDataModel;
        ^
<unknown>:0: error: could not build Objective-C module 'WireExtensionComponents'```

**Comment by mikeger** [comment]
Hey @DaniyalGeek , don't forget to do `carthage bootstrap` in the checkout folder in order to fetch the carthage dependencies.

**Comment by DaniyalGeek** [comment]
can i do also 'pod install'?

**Comment by mikeger** [comment]
Hey, you basically need to do both, `pod install` and `carthage bootstrap` since we use different dependencies from both systems. Generally, you can run `setup.sh` that does it for you.

There is also a README file in the project.

**Comment by mikeger** [comment]
Hey @DaniyalGeek , did you managed to build the project?

**Comment by dosboxd** [comment]
Sadly, I couldn't deal with this error too. I installed pods, after this, I installed carthage and run `carthage bootstrap` string in terminal, after this, I tried to run `sh setup.sh`, but nothing seems to work. Maybe I am doing something wrong?

**Comment by mikeger** [comment]
Hey @dosboxd ! Can you post the detailed error description of what you've seeing? Can you additionally check if the frameworks are successfully downloaded from GH to `wire-ios/Carthage/Build/iOS/` ?

**Comment by dosboxd** [comment]
Hi, I am so sorry for late response, I tried a several times to cleanly download Wire. Last time, I updated ruby(2.0 -> 2.4.2), because there were problems with old version. After that I entered `pod install` and then `carthage bootstrap --platform ios`, it took a lot of time, but it finally showed no errors in console(as I remember), now main problem is signing, but this is another problem to create issue. I try to handle everything by myself and then, if nothing will help, I'll create another issue branch.
![screen shot 2018-02-03 at 5 48 17 am](https://user-images.githubusercontent.com/16291547/35759766-f4f5468c-08a5-11e8-8237-8ae9bb746fb8.png)

This is what './setup.sh' printed in console:
```
Dosbols-MacBook-Air:wire-ios-develop dosbolduysekov$ ./setup.sh
Please update to the latest Carthage version: 0.28.0. You currently are on 0.27.0
ℹ️  Carthage bootstrap. This might take a while...
Please update to the latest Carthage version: 0.28.0. You currently are on 0.27.0
*** Downloading PureLayout.framework binary at "v3.0.0"
*** Downloading ocmock.framework binary at "v3.4"
*** Downloading wire-ios-utilities.framework binary at "18.2.0: It smells like a illegal revolution"
*** Downloading mixpanel-swift.framework binary at "v2.2.2"
*** Skipped installing wire-ios-utilities.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-utilities at "18.2.0"
*** Downloading AFNetworking.framework binary at "2.6.3-iOS8"
*** Downloading wire-ios-message-strategy.framework binary at "75.0.1: buffalos really love eating creme fraiche"
*** Downloading Cartography.framework binary at "Swift 4.0"
*** Skipped installing Cartography.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out Cartography at "1.1.0"
*** Skipped installing mixpanel-swift.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out mixpanel-swift at "v2.2.2"
*** Skipped installing wire-ios-message-strategy.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-message-strategy at "75.0.1"
*** Downloading wire-ios-transport.framework binary at "31.0.4: Crested eagle"
*** Downloading wire-ios-canvas.framework binary at "5.0.2: MODOK VS. Owlman"
*** Skipped installing wire-ios-canvas.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-canvas at "5.0.2"
*** Skipped installing wire-ios-transport.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-transport at "31.0.4"
*** Downloading avs-ios-binaries.framework binary at "Version 4.0.128"
*** Downloading wire-ios-share-engine.framework binary at "61.0.0: I'd like a lush fenugreek and chicken wings burger without cognac, please"
*** Downloading ZipArchive.framework binary at "v2.0.8"
*** Skipped installing wire-ios-share-engine.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-share-engine at "61.0.0"
*** Downloading wire-ios-system.framework binary at "19.1.0: Kyllikki the functional orog from Homberg"
*** Skipped installing wire-ios-system.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-system at "19.1.0"
*** Downloading protobuf-objc.framework binary at "macOS"
*** Skipped installing ZipArchive.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out ZipArchive at "v2.0.8"
*** Downloading wire-ios-images.framework binary at "12.0.1: The One with the Rockin' New Year"
*** Skipped installing wire-ios-images.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-images at "12.0.1"
*** Downloading wire-ios-request-strategy.framework binary at "73.0.0: A giant equal giraffe was spotted near Lübben"
*** Skipped installing wire-ios-request-strategy.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-request-strategy at "73.0.0"
*** Downloading wire-ios-protos.framework binary at "13.0.0: Please estimate the weary otter"
*** Downloading ono.framework binary at "Swift 3.1"
*** Downloading wire-ios-link-preview.framework binary at "7.0.1: The intermediate radical frog"
*** Downloading wire-ios-ziphy.framework binary at "7.0.1: From Nanning to Papeete"
*** Skipped installing wire-ios-link-preview.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-link-preview at "7.0.1"
*** Skipped installing wire-ios-ziphy.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-ziphy at "7.0.1"
*** Downloading PINCache.framework binary at "Swift 3.1"
*** Downloading HockeySDK-iOS.framework binary at "5.0.0"
*** Downloading FLAnimatedImage.framework binary at "1.0.12-wire"
*** Downloading libPhoneNumber-iOS.framework binary at "Swift 3.1"
*** Downloading ios-snapshot-test-case.framework binary at "Swift 4.0"
*** Downloading FormatterKit.framework binary at "Swift 3.0.2"
*** Downloading onepassword-app-extension.framework binary at "Swift 3.0.2"
*** Downloading Marklight.framework binary at "Wire Version 1 Beta 9"
*** Skipped installing Marklight.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out Marklight at "1.0.9"
*** Downloading wire-ios-sync-engine.framework binary at "142.0.7: Wiesloch"
*** Downloading TTTAttributedLabel.framework binary at "Swift 3.0.2"
*** Skipped installing wire-ios-sync-engine.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-sync-engine at "142.0.7"
*** Downloading Classy.framework binary at "Swift 3.0.2"
*** Downloading CocoaLumberjack.framework binary at "3.3.0"
*** Skipped installing ios-snapshot-test-case.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out ios-snapshot-test-case at "2.1.4-swift3.1"
*** Downloading wire-ios-data-model.framework binary at "89.0.6: What would Éva Tardos do?"
*** Skipped installing CocoaLumberjack.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out CocoaLumberjack at "3.3.0"
*** Downloading wire-ios-cryptobox.framework binary at "11.0.1: You should never harm in Huai'an"
*** Skipped installing wire-ios-cryptobox.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-cryptobox at "11.0.1"
*** Skipped installing wire-ios-data-model.framework binary due to the error:
	"Incompatible Swift version - framework was built with 4.0 (swiftlang-900.0.65.2 clang-900.0.37) and the local version is 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)."
*** Checking out wire-ios-data-model at "89.0.6"
*** xcodebuild output can be found in /var/folders/by/wq16lsbx15d1btccz65q397r0000gn/T/carthage-xcodebuild.tl3xmI.log
*** Building scheme "Cartography-iOS" in Cartography.xcworkspace
*** Building scheme "CocoaLumberjack-iOS" in Lumberjack.xcworkspace
*** Building scheme "CocoaLumberjackSwift-iOS" in Lumberjack.xcworkspace
*** Building scheme "FBSnapshotTestCase iOS" in FBSnapshotTestCase.xcworkspace
*** Building scheme "Marklight" in Marklight Sample.xcworkspace
*** Building scheme "Marklight" in Marklight Sample.xcworkspace
*** Building scheme "Mixpanel" in MixpanelDemo.xcworkspace
*** Building scheme "WireCanvas" in WireCanvas.xcodeproj
*** Building scheme "WireLinkPreview" in WireLinkPreview.xcodeproj
*** Building scheme "WireSystem" in WireSystem.xcodeproj
*** Building scheme "WireCryptobox" in WireCryptobox.xcodeproj
*** Building scheme "WireUtilities" in WireUtilities.xcodeproj
*** Building scheme "WireImages" in WireImages.xcodeproj
*** Building scheme "WireTransport" in WireTransport.xcodeproj
*** Building scheme "WireDataModel" in WireDataModel.xcodeproj
*** Building scheme "WireRequestStrategy" in WireRequestStrategy.xcodeproj
*** Building scheme "WireMessageStrategy" in WireMessageStrategy.xcodeproj
*** Building scheme "WireShareEngine" in WireShareEngine.xcodeproj
*** Building scheme "WireSyncEngine" in WireSyncEngine.xcodeproj
*** Building scheme "ziphy" in ziphy.xcodeproj
*** Building scheme "ZipArchive-iOS" in ZipArchive.xcodeproj

ℹ️  Downloading AVS library...
ℹ️  No custom AVS binary specified

ℹ️  Check that bundler is installed... (requires SUDO)

ℹ️  Pod install. This might take a while...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'bundler' (>= 0) among 53 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/bundle:22:in `<main>'

ℹ️  Downloading additional assets...
No access to assets

✅  Wire project was set up, you can now open Wire-iOS.xcworkspace
```

**Comment by mikeger** [comment]
@dosboxd from your log I see that you are using the most recent Xcode, which we are not supporting unfortunately yet. Try to downgrade to `9.0.1 (9A1004)` and clean install again.
